### ISSUE TITLE
rM2 may not like the svg file

### ISSUE THREAD

**Issue by llinfeng** [steka/reMarkable_templates#1]
With both `Whitelines_lines.png` and `Whitelines_lines.svg` + proper `template.json` entries, the template failed to render on my rM2. Yet, deleting the `Whitelines_lines.svg` revives the template.

Thanks a lot for sharing the JSON piece. The `"Custom"` category mentioned in [this Reddit post](https://www.reddit.com/r/RemarkableTablet/comments/jr9jn3/tired_of_trying_to_find_custom_templates_just/) does create a new tab as a new home for all _useful_ templates :)

**Comment by steka** [comment]
Hmmm, strange!?.

My first guess was that it was related to the new firmware (2.4.1.30), so I tested it on my rM1 that got the updated firmware, but that works as intended.

I will look at this when I get my rM2 (hopefully in a couple of weeks, batch 8).

**Comment by llinfeng** [comment]
Not sure if this is a surprise for you. The following intrusive watermark is inserted when I preview the notes with custom templates on my Windows machine. This could have been a dealbreaker for me, as I can at best see the template while writing on rM2. The exported PDF has a perfectly white background (no underlying template at all).
![image](https://user-images.githubusercontent.com/5890407/99155783-2058d600-2689-11eb-9f6a-880c5d302e5c.png)
Thankfully, these warnings about the template do not get exported. 


Good luck with a fast shipment for rM2 :)

**Comment by steka** [comment]
That is unfortunately a limitation of the Windows application. It simply doesn't known anything about custom templates.
The way to include them into the exported document is to export them from the reMarkable instead.
Just send the page or document by email to yourself, then the custom template(s) will be included.

**Comment by llinfeng** [comment]
Aha, that's a valid point! Among all software pieces provided by reMarkable, the one that ships with the tablet should have received most care. Emailing from reMarkable works as intended!

**Comment by steka** [comment]
I just tested on my reMarkable2, and both templates works just fine,
Could perhaps be because my reMarkable has v2.5.0.27.

**Comment by llinfeng** [comment]
Oh, another update rolled out? Will see how long it takes to reach my device 👍 

Though, with v2.4.1.30, it takes a two-step process to get the template to work with both `png` and `svg` files:
1. Upload only the `png` file. The template should work. (Uploading `png`+`svg` together may yield the error [reported previously](https://github.com/steka/reMarkable_templates/issues/1#issuecomment-727258059).)
2. Reboot and upload the `svg` file, the template on the rM2 device should work by now.

I will close this issue as there is a workaround for v2.4.1.30, and the issue may go away with v2.5.0.27.

----

PS: I have been happy with the my [letter-sized-notepad-remplate](https://www.dropbox.com/sh/mhd89tu5ecnd70w/AABr9DlSJ874qX6OQeeEXLuja?dl=0), where the line-spacing on rM2 matches with a regular letter-sized notepad.
