### ISSUE TITLE
Add License

### ISSUE THREAD

**Issue by Eeems** [steka/reMarkable_templates#2]
There doesn't seem to be a license included with this. So it's not clear what users can and cannot do with the contents of this repository.

**Comment by Eeems** [comment]
Poke?

**Comment by steka** [comment]
A license had been added.

[![ko-fi](https://ko-fi.com/img/githubbutton_sm.svg)](https://ko-fi.com/K3K14JEJS)

**Comment by steka** [comment]
A license had been added.

[![ko-fi](https://ko-fi.com/img/githubbutton_sm.svg)](https://ko-fi.com/K3K14JEJS)
